---
name: weather_app
description: "A simple weather app build in flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  geolocator: ^14.0.2
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  geocoding: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins/Poppins-Italic.ttf
        weight: 400
        style: italic

  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat/Montserrat-Regular.ttf
        weight: 400
      - asset: fonts/Montserrat/Montserrat-Medium.ttf
        weight: 500
      - asset: fonts/Montserrat/Montserrat-Bold.ttf
        weight: 700
      - asset: fonts/Montserrat/Montserrat-Italic.ttf
        weight: 400
        style: italic
